### ISSUE TITLE
add content to README.md

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-only-bot#65]
let’s merge #44 first, but then it would be nice if you could create a PR for the `README.md` file which explains what the project (currently) does, how to set it up, etc. That makes it more accessible to others, and it’s Open Source best practise to always have a great README :) You can take lots of the content from https://github.com/hoodiehq/first-timers-only-bot and also reference it, explaining where the project currently is in the process

**Comment by agonzalez0515** [comment]
Merged README pull request. Now I'm working on fleshing out the Glitch section.
